
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 13 15:14:23 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPENB = 5;
  public static final int MULT = 30;
  public static final int ASGN = 17;
  public static final int CHAR = 12;
  public static final int REPEAT = 15;
  public static final int INT = 11;
  public static final int CLOSEP = 4;
  public static final int LESS = 22;
  public static final int MINUS = 29;
  public static final int GRET = 26;
  public static final int WRITE = 19;
  public static final int AND = 21;
  public static final int INTCONST = 32;
  public static final int OR = 20;
  public static final int BOOL = 14;
  public static final int COMMA = 9;
  public static final int CLOSEB = 6;
  public static final int SEMICOL = 8;
  public static final int DIV = 31;
  public static final int UNTIL = 16;
  public static final int GRETEQ = 27;
  public static final int PLUS = 28;
  public static final int LESSEQ = 23;
  public static final int MAIN = 2;
  public static final int ID = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int REAL = 13;
  public static final int COL = 7;
  public static final int READ = 18;
  public static final int CHARCONST = 35;
  public static final int REALCONST = 33;
  public static final int BOOLCONST = 34;
  public static final int DIFF = 25;
  public static final int OPENP = 3;
  public static final int ISEQ = 24;
}

